### ISSUE TITLE
Switch month automatically

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/white-rabbit#50] opened 2020-12-01 05:48 UTC
# Situation

When running from the last day of a month to the first day of the next month, WR should automatically switch the view to the next month.

# Acceptance Criteria

1. WR GUI automatically switches to the next month when the first day of a new month starts:
    * in the month drop-down box
    * in the month detail view
    * all calculated fields

**Comment by kaklakariada** [comment] 2020-12-05 11:50
Duplicate of #51

**Closed** 2020-12-05 17:17 UTC
Labels: bug
